version: "3"
networks:
  slack-bot-dev-network:

services:
  slack_bot_dev:
    build: .
    deploy:
    restart: unless-stopped
    environment:
      - Bot__BotKey=${Bot__BotKey}
      - Bot__AllowedUser=${Bot_AllowedUser}
      - Bot__ScriptsPath=/scripts
    volumes:
      - ./Command.Bot.Core.Tests/Samples:/scripts
    networks:
      - slack-bot-dev-network
